### ISSUE TITLE
Feature request: make Jax work better with dependency managers

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#16658]
Running a dependency manager like Poetry with Jax seems to be extremely slow, especially when `cuda` is specified.  I think this is [explained here](https://python-poetry.org/docs/faq/#why-is-the-dependency-resolution-process-slow):

> This is due to the fact that not all libraries on PyPI have properly declared their metadata and, as such, they are not available via the PyPI JSON API. At this point, Poetry has no choice but to download the packages and inspect them to get the necessary information. This is an expensive operation, both in bandwidth and time, which is why it seems this is a long process.

Would it be possible to produve PyPI JSON information?

I realize that currently Jax has a setup.py, which generates various dependencies.  Would it be possible to generate these dependencies at release time and then use them to populate `pyproject.toml` instead?  This would reduce the burden on PyPI and on users who wait 5 minutes (while every jaxlib with every cuda version downloads) just to resolve dependencies.

**Comment by PhilipVinc** [comment]
Probably the biggest problem is not even jax, but `jaxlib`, which weights much more.

**Comment by hawkinsp** [comment]
I'm not sure concretely what the ask is here. As best I can tell, pypi's JSON information is available for `jax`:
e.g.,

https://pypi.org/pypi/jax/json
https://pypi.org/pypi/jaxlib/json

Can you say more about what you want us to do?

**Comment by NeilGirdhar** [comment]
@PhilipVinc Wow, thanks for digging into this!  What you're saying makes sense, but we could ask the Poetry people to comment if not.  All I know is that `poetry update` with a `jax[cuda]` dependency takes a very long time and initiates many downloads.

**Comment by hawkinsp** [comment]
If the `cuda` build is the problem, well, that's not hosted on pypi at the moment. We have plans to do that in motion, but it requires restructuring the `cuda` part into a plugin of `jaxlib` rather than being a variant of that. I suspect that would solve your problem, because then you'd be able to query pypi for the dependency structure.

**Comment by jakevdp** [comment]
Is the issue that extra dependencies like `[cuda]` are specified in `setup.py` rather than in `pyproject.toml`?

**Comment by PhilipVinc** [comment]
I am relatively confident, that the problem is that `jax` is distributed as a source-only distribution instead of a (platform-independent) wheel. In a sense, a wheel for a 'simple' package like jax will have the `setup.py` already executed, and dependencies precomputed. a source distribution does not.

Source distributions do not contain METADATA, while wheels do.

PyPi parses METADATA to fill in the field `dist-requires` served over json.

I just tried building jax myself (`python -m build .`) and checked the content of the wheel and it indeed contains the relevant files.

PyProject.toml is not required to have pypi serve metadata correctly.

The fix is as simple as editing your release process to build and upload the jax wheel.

**Comment by NeilGirdhar** [comment]
This may have been my error.  I forgot that I was using a non-PyPI source for the wheels.  Here's my working Jax install using Poetry for Linux and Mac in case it helps anyone:
```toml
[tool.poetry.dependencies]
jax = [
    {version = '>=0.4.13', extras = ['cuda'], platform = 'linux', source="jax_pep503"},
    {version = '>=0.4.13', platform = 'darwin', source="PyPI"}
]
jaxlib = [
    {version = '>=0.4.13', platform = 'linux', source="jax_pep503"},
    {version = '>=0.4.13', platform = 'darwin', source="PyPI"}
]

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"

[[tool.poetry.source]]
name = "jax_pep503"
url = "https://jorenham.github.io/jax_pep503/"
priority = "explicit"
```
